# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    stripe_secret_key: 'sk_test_51MeOmdAImipVJMp4npAZs3vzcocjTuiSr65s2gv5Wlwlt2D0kKf3CWSWoNuQMKXVT7vklxqUV7MlxKGCUlqDUB0e00Uqss47MZ'
    stripe_public_key: 'pk_test_51MeOmdAImipVJMp4Uada2wrItOgdiE1wysZnHzYxdQ3UHNWs1EIbpUPf6oOoSbOZZ2BTFlpK36tmevt177atxjDQ00eoPOLxPD'
services:
    Stripe\Stripe:
        factory: ['Stripe\Stripe', 'setApiKey']
        arguments: ['%stripe_secret_key%']
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/'
        
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
    
    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
