name: Symfony UX

on:
    pull_request:
    push:
        branches:
            - 'main'

jobs:
    coding-style:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Prettier
              run: |
                  yarn
                  yarn run check-format

    tests:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - name: Install dependencies
              run: yarn
            - name: Tests
              run: yarn test
